export default {
  GET_TASK_LIST_REQUEST: 'GET_TASK_LIST_REQUEST',
  GET_TASK_LIST_SUCCESS: 'GET_TASK_LIST_SUCCESS',
  GET_TASK_LIST_FAILURE: 'GET_TASK_LIST_FAILURE',

  ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
  ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',

  UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
  UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
  UPDATE_TASK_FAILURE: 'UPDATE_TASK_FAILURE',

  CHANGE_SORT_FIELD: 'CHANGE_SORT_FIELD',
  CHANGE_SORT_DIRECTION: 'CHANGE_SORT_DIRECTION',
  CHANGE_PAGE: 'CHANGE_PAGE',
};
